# Generated by Django 2.2 on 2020-03-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.TextField(blank=True, help_text='如果设置的不是 HTML 类型，可以为空', max_length=500, verbose_name='内容'),
        ),
    ]
